services:
  olim:
    image: ghcr.io/cyllective/olim:latest
    restart: unless-stopped
    environment:
      - DB_PATH=/data/olim.sqlite
    #  - DEBUG=1
    volumes:
      - ./olim_data:/data
    ports:
      - 127.0.0.1:8080:8080